import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const load=(file)=>JSON.parse(readFileSync(path.join(root,file),'utf8'));
const save=(file,data)=>writeFileSync(path.join(root,file),`${JSON.stringify(data,null,2)}\n`);
const unwrap=(raw)=>Array.isArray(raw)?raw:raw.items;
const rewrap=(raw,items)=>Array.isArray(raw)?items:{...raw,items};
const assert=(condition,message)=>{if(!condition)throw new Error(message)};
const precheck=load('ibrazx40_3_removal_precheck.json');
const mainRaw=load('items.json'), publicRaw=load('client/public/items.json'), statsBefore=load('stats.json');
const main=unwrap(mainRaw), published=unwrap(publicRaw);
const removalIds=precheck.requested_removal_ids, removalSet=new Set(removalIds), protectedIds=precheck.protected.map(row=>row.id);
const inScope=(item)=>item&&item.source==='القانون الدولي العام'&&[item.link_telegram,item.link_drive,item.link_direct].some(link=>String(link??'').includes('ibrazx40'));
assert(main.length===11286&&published.length===11286,'العدد القبلي لا يطابق الحالة المعتمدة 11,286.');
assert(new Set(main.map(item=>item.id)).size===main.length,'توجد IDs مكررة في النسخة الرئيسية قبل الحذف.');
assert(new Set(published.map(item=>item.id)).size===published.length,'توجد IDs مكررة في النسخة المنشورة قبل الحذف.');
const mainById=new Map(main.map(item=>[item.id,item])), publicById=new Map(published.map(item=>[item.id,item]));
for(const id of removalIds){assert(mainById.has(id),`المعرف غير موجود في الرئيسية: ${id}`);assert(publicById.has(id),`المعرف غير موجود في المنشورة: ${id}`);assert(inScope(mainById.get(id)),`المعرف خارج مصدر ibrazx40: ${id}`);}
for(const id of protectedIds)assert(mainById.has(id)&&publicById.has(id),`السجل المحمي مفقود: ${id}`);
const removed=removalIds.map(id=>mainById.get(id));
const nextMain=main.filter(item=>!removalSet.has(item.id)), nextPublic=published.filter(item=>!removalSet.has(item.id));
assert(nextMain.length===11283&&nextPublic.length===11283,'العدد البعدي لا يطابق 11,283.');
assert(nextMain.every(item=>!removalSet.has(item.id))&&nextPublic.every(item=>!removalSet.has(item.id)),'بقي أحد المعرفات الثلاثة بعد التصفية.');
assert(protectedIds.every(id=>nextMain.some(item=>item.id===id)&&nextPublic.some(item=>item.id===id)),'فقد أحد السجلات المحمية.');
const category=(item)=>String(item.category??'عام');
const countBy=(list,key,fallback)=>Object.fromEntries([...list.reduce((map,item)=>{const name=String(item[key]??fallback).trim()||fallback;map.set(name,(map.get(name)??0)+1);return map},new Map()).entries()].sort((a,b)=>a[0].localeCompare(b[0],'ar')));
const stats={total_items:nextMain.length,qadaa_count:nextMain.filter(item=>/قضاء|قضائي/.test(category(item))).length,nizam_count:nextMain.filter(item=>/نظام|لائحة|تشريع/.test(category(item))).length,mohama_count:nextMain.filter(item=>/محاماة|محامي/.test(category(item))).length,other_count:0,books_count:nextMain.length,audio_count:0,video_count:0,categories:countBy(nextMain,'category','عام'),sources:countBy(nextMain,'source','غير محدد'),file_types:countBy(nextMain,'file_type','غير محدد'),featured_count:nextMain.filter(item=>item.is_featured).length,with_download_links:nextMain.filter(item=>item.link_telegram||item.link_drive||item.link_direct).length};
stats.other_count=Math.max(0,stats.total_items-stats.qadaa_count-stats.nizam_count-stats.mohama_count);
assert(nextMain.filter(inScope).length===130,'عدد مصدر ibrazx40 بعد الحذف لا يطابق 130.');
save('items.json',rewrap(mainRaw,nextMain));save('client/public/items.json',rewrap(publicRaw,nextPublic));save('stats.json',stats);save('client/public/stats.json',stats);
const hookPath=path.join(root,'client/src/hooks/useItems.ts');const hookBefore=readFileSync(hookPath,'utf8');const cacheBefore='iirmll-duplicate-removal-9-2026-08-25',cacheAfter='ibrazx40-targeted-removal-3-2026-08-25';const hookAfter=hookBefore.replaceAll(cacheBefore,cacheAfter);assert(hookAfter!==hookBefore,'لم يعثر على معلمة كسر الكاش المتوقعة.');writeFileSync(hookPath,hookAfter);
const execution={generated_at:new Date().toISOString(),total_before:main.length,total_after:nextMain.length,ibraz_before:main.filter(inScope).length,ibraz_after:nextMain.filter(inScope).length,removed_count:removed.length,removed:removed.map(item=>({id:item.id,title:item.title,source:item.source,category:item.category,link_telegram:item.link_telegram})),protected_ids_verified:protectedIds,stats_before_total:statsBefore.total_items,cache_before:cacheBefore,cache_after:cacheAfter};
save('ibrazx40_3_removal_execution.json',execution);console.log(JSON.stringify(execution,null,2));
