import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';
const root=process.cwd(),load=(file)=>JSON.parse(readFileSync(path.join(root,file),'utf8'));
const precheck=load('ibrazx40_3_removal_precheck.json'),execution=load('ibrazx40_3_removal_execution.json'),validation=load('ibrazx40_3_removal_post_validation.json');
const commit=execFileSync('git',['rev-parse','--short','HEAD'],{cwd:root,encoding:'utf8'}).trim();const tag=execFileSync('git',['rev-parse','--short','stable-clean-state-11283-2026-08-25'],{cwd:root,encoding:'utf8'}).trim();
const lines=['تقرير تنفيذ الحذف المحدد — مصدر ibrazx40 / القانون الدولي العام','التاريخ: 2026-08-25','','النطاق','اقتصر الحذف على المعرفات الثلاثة المعتمدة صراحة. لم يستخدم حذف بالكلمات المفتاحية أو بالعناوين أو بالتطبيع العام، ولم يتغير أي سجل آخر أو أي مصدر آخر.','','التحقق القبلي','البند | النتيجة',`إجمالي المكنز قبل الحذف | ${precheck.total_before}`,`سجلات ibrazx40 قبل الحذف | ${precheck.ibraz_before}`,`المعرفات المطلوبة | ${precheck.requested_removal_ids.length}`,`المعرفات الموجودة فعلياً | ${precheck.requested_removal_ids.length-precheck.missing_removal_ids.length}`,`المعرفات المفقودة | ${precheck.missing_removal_ids.length}`,`المعرفات ذات مصدر غير مطابق | ${precheck.wrong_source_removal_ids.length}`,'','المعرفات المحذوفة والعناوين الفعلية','id | العنوان | المصدر | التصنيف',...execution.removed.map(row=>`${row.id} | ${row.title} | ${row.source} | ${row.category}`),'','النتيجة بعد التنفيذ','البند | النتيجة',`عدد المحذوف فعلياً | ${execution.removed_count}`,`إجمالي المكنز بعد الحذف | ${execution.total_after}`,`سجلات ibrazx40 بعد الحذف | ${execution.ibraz_after}`,`المعرفات المحذوفة المتبقية في الرئيسية | ${validation.removed_ids_remaining_main.length}`,`المعرفات المحذوفة المتبقية في المنشورة | ${validation.removed_ids_remaining_published.length}`,`تطابق items.json والنسخة المنشورة | ${validation.main_published_same_ids?'نعم':'لا'}`,`سلامة JSON وغياب IDs المكررة | ${validation.no_duplicate_ids_main&&validation.no_duplicate_ids_published?'نعم':'لا'}`,`فقد سجل خارج القائمة | ${validation.no_external_loss?'لا':'نعم'}`,'','السجلات المحمية',`بقاء المعرفات السبعة المحمية | ${validation.protected_ids_missing_main.length===0&&validation.protected_ids_missing_published.length===0?'مؤكد':'غير مؤكد'}.`,'','الفحوص التقنية','نجح فحص TypeScript والبناء الإنتاجي. ظهرت المعاينة بإجمالي 11,283 مادة، واختبر فلتر مصدر القانون الدولي العام وأظهر 130 مادة، كما تأكد من بيانات المعاينة بقاء السجلات المحمية وعدم وجود المعرفات المحذوفة.','','النسخة الاحتياطية والتثبيت المحلي',`النسخة الاحتياطية: backups/ibrazx40_3_targeted_removal_2026-08-25/`,`الـcommit المحلي: ${commit}.`,`الوسم المحلي: stable-clean-state-11283-2026-08-25 (${tag}).`,`بصمة items.json بعد إعادة التشغيل: ${validation.hashes.items_main}.`,`بصمة stats.json بعد إعادة التشغيل: ${validation.hashes.stats_main}.`,'أعيد تشغيل المعاينة مرة واحدة بعد التثبيت، وظلت الأعداد والبصمات والحذوف ثابتة.','','حدود التنفيذ','لم يُنشأ checkpoint مُدار، ولم تُنفذ مزامنة GitHub أو Push أو نشر للموقع.',''];
writeFileSync(path.join(root,'ibrazx40_3_removal_execution_report.txt'),lines.join('\n'),'utf8');
console.log(JSON.stringify({report:'ibrazx40_3_removal_execution_report.txt',total_after:execution.total_after,ibraz_after:execution.ibraz_after,commit,tag},null,2));
