import { readFile, writeFile } from 'node:fs/promises';
const root=process.cwd(); const exportPath='/home/ubuntu/upload/pasted_file_k9XHUn_result.json';
const normalize=(v='')=>String(v).replace(/\.[A-Za-z0-9]{2,5}$/,'').normalize('NFKD').replace(/[\u064B-\u065F\u0670]/g,'').replace(/[أإآٱ]/g,'ا').replace(/ة/g,'ه').replace(/ى/g,'ي').toLowerCase().replace(/[^\p{L}\p{N}]/gu,'');
const clean=(v='')=>String(v).replace(/\.[A-Za-z0-9]{2,5}$/,'').replace(/[_-]+/g,' ').replace(/\s+/g,' ').trim();
const positive=/قضائ|قضاء|محكم|محام|مرافع|دعوى|تنفيذ|نظام|لائح|قانون|تشريع|تحكيم|اثبات|شهاد|بينه|اقرار|قرينه|جناي|جريم|عقوب|نياب|تحقيق|توقيف|سجن|دستور|دول|تجار|شرك|عقد|التزام|عقار|تملك|ايجار|افلاس|تامين|منازع|قضيه|حكم|عدال|ديوان|مظالم|موثق|توثيق|سجل|ضريب|جمرك|عمال|وظيف|ادار|احوال شخصي|طلاق|خلع|حضان|نفق|مواريث|تركات|وقف/;
const negative=/قضاء وقدر|قضاء الحاجة|قضاء على (مرض|مشك|ظاهر)|تحليل جغرافي|قضاء الكاظمية|القاضي عياض|القاضي الفاضل|تفسير|عقيدة|تجويد|قراءات|نحو|صرف|بلاغة|شعر|حديث نبوي|تاريخ اسلامي|سيرة نبوية|طب |هندس|كيمياء|بيولوج|فيزياء|رياضيات|مدرس|تعليم|جامع.*(الطلاب|الطالبات)|اختبار|ملخص|محاضرة/;
const category=(title)=>/تحكيم|وساط/.test(title)?'التحكيم والوساطة':/محام/.test(title)?'المحاماة':/اثبات|شهاد|بينه|اقرار|قرينه/.test(title)?'الإثبات والشهادة':/جناي|جريم|عقوب|سجن|نياب|تحقيق/.test(title)?'القانون الجنائي':/ادار|ديوان|مظالم|وظيف/.test(title)?'القضاء الإداري':/احوال شخصي|طلاق|خلع|حضان|نفق|مواريث|تركات/.test(title)?'الأحوال الشخصية':/عقار|ايجار|تملك/.test(title)?'القانون المدني':/تجار|شرك|افلاس|تجار/.test(title)?'القانون التجاري':/نظام|لائح|تشريع|قانون/.test(title)?'الأنظمة والتشريعات':/قضاء|محكم|دعوى|مرافع|تنفيذ/.test(title)?'المحاكم والمرافعات':'الأبحاث القانونية والقضائية';
const currentRaw=JSON.parse(await readFile(`${root}/items.json`,'utf8'));const current=Array.isArray(currentRaw)?currentRaw:currentRaw.items;const existing=new Set(current.map(x=>normalize(x.title)).filter(Boolean)); const exportData=JSON.parse(await readFile(exportPath,'utf8'));const seen=new Set(),selected=[],excluded=[];
for(const message of exportData.messages||[]){if(message.type!=='message'||!message.file_name)continue;const title=clean(message.file_name);const key=normalize(title);const text=title.toLowerCase();if(!key||title.length<9){excluded.push({id:message.id,title,reason:'عنوان قصير أو فارغ'});continue;}if(negative.test(text)){excluded.push({id:message.id,title,reason:'دلالة غير قانونية مستبعدة'});continue;}if(!positive.test(text)){excluded.push({id:message.id,title,reason:'لا دلالة قانونية أو قضائية كافية'});continue;}if(existing.has(key)){excluded.push({id:message.id,title,reason:'عنوان موجود في المكنز'});continue;}if(seen.has(key)){excluded.push({id:message.id,title,reason:'عنوان مكرر داخل التصدير'});continue;}seen.add(key);selected.push({telegram_message_id:message.id,date:message.date,title,category:category(text),material_type:'عنوان مرجعي',file_type:'عنوان',source:'مكتبة القانون',publisher:'قناة مكتبة القانون',author:'',investigator:'',year:'',link_telegram:'',link_drive:'',link_direct:'',file_size:'',pages_count:'',is_featured:false,download_links_count:0});}
const categories=Object.fromEntries([...selected.reduce((m,x)=>m.set(x.category,(m.get(x.category)||0)+1),new Map()).entries()].sort((a,b)=>b[1]-a[1]));const result={created_at:new Date().toISOString(),input_messages:(exportData.messages||[]).length,selected_count:selected.length,excluded_count:excluded.length,categories,selected,excluded};await writeFile(`${root}/lawlibrary_channel_title_candidates.json`,`${JSON.stringify(result,null,2)}\n`);await writeFile(`${root}/lawlibrary_channel_title_candidates.txt`,['مرشحات العناوين من تصدير قناة مكتبة القانون',`إجمالي رسائل التصدير: ${result.input_messages}`,`عناوين مرشحة عالية الصلة وغير مكررة: ${selected.length}`,`مستبعدات: ${excluded.length}`,'','التوزيع بحسب التصنيف:',...Object.entries(categories).map(([k,v])=>`- ${k}: ${v}`),'','أول 40 عنواناً مرشحاً:',...selected.slice(0,40).map(x=>`- [${x.telegram_message_id}] ${x.title}`)].join('\n'));console.log(JSON.stringify({selected:selected.length,excluded:excluded.length,categories},null,2));
