import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
const root=process.cwd();
const raw=JSON.parse(readFileSync(path.join(root,'items.json'),'utf8'));
const items=Array.isArray(raw)?raw:raw.items;
const removalIds=['intlaw_145','intlaw_154','intlaw_269'];
const protectedIds=['intlaw_57','intlaw_58','intlaw_59','intlaw_87','intlaw_138','intlaw_37','intlaw_65'];
const lookup=new Map(items.map(item=>[item.id,item]));
const rows=removalIds.map(id=>({id,exists:lookup.has(id),...(lookup.get(id)??{})}));
const protectedRows=protectedIds.map(id=>({id,exists:lookup.has(id),...(lookup.get(id)??{})}));
const validSource=(item)=>item&&item.source==='القانون الدولي العام'&&[item.link_telegram,item.link_drive,item.link_direct].some(link=>String(link??'').includes('ibrazx40'));
const missing=rows.filter(row=>!row.exists).map(row=>row.id);
const wrongSource=rows.filter(row=>row.exists&&!validSource(row)).map(row=>row.id);
const missingProtected=protectedRows.filter(row=>!row.exists).map(row=>row.id);
const ibrazCount=items.filter(validSource).length;
const report={generated_at:new Date().toISOString(),total_before:items.length,ibraz_before:ibrazCount,requested_removal_ids:removalIds,removals:rows.map(row=>({id:row.id,exists:row.exists,title:row.title??'',source:row.source??'',category:row.category??'',link_telegram:row.link_telegram??''})),protected:protectedRows.map(row=>({id:row.id,exists:row.exists,title:row.title??'',source:row.source??'',category:row.category??''})),missing_removal_ids:missing,wrong_source_removal_ids:wrongSource,missing_protected_ids:missingProtected};
writeFileSync(path.join(root,'ibrazx40_3_removal_precheck.json'),`${JSON.stringify(report,null,2)}\n`);
console.log(JSON.stringify({total_before:items.length,ibraz_before:ibrazCount,requested:removalIds.length,found:removalIds.length-missing.length,missing,wrongSource,missingProtected},null,2));
if(items.length!==11286||ibrazCount!==133||missing.length||wrongSource.length||missingProtected.length)process.exit(1);
